from eda_utils import *

PAGE_TITLE = "Pham Learning Report"
PAGE_ICON = "📘"
LAYOUT = "wide"
SIDEBAR_STATE = "auto"

SCORE_GOOD = 75
SCORE_BAD = 60

SUBJECT_COLOURS = {
    "Math": "#1E90FF",
    "Functions": "#1E90FF",
    "Data Management": "#1E90FF",
    "French": "#FF5100",
    "English": "#28A745",
    "Science": "#17A2B8",
    "Chemistry": "#6F42C1",
    "Physics": "#FD7E14",
    "Biology": "#20C997",
}

CUSTOM_STOPWORDS = {
    # Standard filler words
    "i",
    "he",
    "she",
    "they",
    "him",
    "her",
    "them",
    "we",
    "us",
    "the",
    "a",
    "an",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "shall",
    "can",
    "to",
    "of",
    "in",
    "for",
    "on",
    "with",
    "at",
    "by",
    "from",
    "as",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "between",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "each",
    "every",
    "both",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "just",
    "also",
    "now",
    "and",
    "but",
    "or",
    "if",
    "because",
    "until",
    "while",
    "this",
    "that",
    "these",
    "those",
    "what",
    "which",
    "who",
    "whom",
    "its",
    "it",
    "he",
    "she",
    "they",
    "them",
    "his",
    "her",
    "their",
    "our",
    "your",
    "my",
    "we",
    # Tutoring report phrases
    "homework",
    "worksheet",
    "worksheets",
    "scored",
    "student",
    "students",
    "session",
    "sessions",
    "today",
    "lesson",
    "worked",
    "work",
    "working",
    "works",
    "practice",
    "practiced",
    "practicing",
    "reviewed",
    "review",
    "reviewing",
    "learned",
    "learn",
    "learning",
    "taught",
    "teach",
    "teaching",
    "covered",
    "cover",
    "discussed",
    "discuss",
    "discussing",
    "went",
    "go",
    "going",
    "over",
    # Common tutor descriptors (generic praise/assessment)
    "well",
    "good",
    "great",
    "excellent",
    "nice",
    "better",
    "best",
    "able",
    "ability",
    "capable",
    "encouraged",
    "encourage",
    "encouraging",
    "continue",
    "continued",
    "continues",
    "continuing",
    "needs",
    "need",
    "needed",
    "overall",
    "generally",
    "specifically",
    "particularly",
    # Generic verbs
    "understand",
    "understands",
    "understanding",
    "understood",
    "complete",
    "completed",
    "completing",
    "completes",
    "completion",
    "improve",
    "improved",
    "improving",
    "improvement",
    "improvements",
    "show",
    "showed",
    "shown",
    "showing",
    "shows",
    "demonstrate",
    "demonstrated",
    "demonstrates",
    "help",
    "helped",
    "helping",
    "helps",
    "focus",
    "focused",
    "focusing",
    "focuses",
    "make",
    "made",
    "making",
    "makes",
    "get",
    "gets",
    "got",
    "getting",
    "use",
    "used",
    "using",
    # Time references
    "week",
    "weeks",
    "month",
    "months",
    "day",
    "days",
    "time",
    "times",
    "next",
    "last",
    "previous",
    "upcoming",
    "recent",
    "recently",
    # Transition words
    "however",
    "moreover",
    "furthermore",
    "additionally",
    "therefore",
    "consequently",
    "meanwhile",
    "although",
    "nevertheless",
    "still",
}
